name: BunzeeHorse
version: ${project.version}
main: dev.tebbot.bunzeehorse.Main
authors: [ NotTebbot_ ]
description: Bunzee horse gui
commands:
  horse:
    description: The main horse
    aliases: [h]